export const USER_REGISTRATION_PENDING = "USER_REGISTRATION_PENDING";
export const USER_REGISTRATION_REJECT = "USER_REGISTRATION_REJECT";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";

export const USER_LOGIN_PENDING = "USER_LOGIN_PENDING";
export const USER_LOGIN_REJECT = "USER_LOGIN_REJECT";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const IS_LOGIN_Auth = "IS_LOGIN_Auth";
